---
- name: Add nvidia CUDA repo
  yum_repository:
    name: nvidia-cuda-rhel9-x86_64
    description: NVIDIA CUDA repo for RHEL 9
    baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64
    gpgcheck: yes
    gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/D42D0685.pub

- import_tasks: management-library.yml

- import_tasks: container-tools.yml

- import_tasks: systemd.yml

- name: Validate DCGM metrics endpoint is working
  ansible.builtin.shell: set -o pipefail && curl -s localhost:9400/metrics | grep 'DCGM_FI_DEV_SM_CLOCK{'
  register: dcgm_metrics_check
  failed_when: dcgm_metrics_check.rc != 0
  changed_when: false
