---
- name: Add nvidia CUDA repo
  yum_repository:
    name: nvidia-cuda-rhel9
    description: NVIDIA CUDA repo for RHEL 9
    baseurl: "{{dcgm_exporter_nvidia_repo_url}}/$basearch/"
    gpgcheck: yes
    gpgkey: "{{dcgm_exporter_nvidia_repo_url}}/D42D0685.pub"

- import_tasks: driver.yml

- import_tasks: management-library.yml

- import_tasks: container-tools.yml

- import_tasks: systemd.yml

- name: Validate DCGM metrics endpoint is working
  ansible.builtin.shell: set -o pipefail && curl -s localhost:9400/metrics | grep 'DCGM_FI_DEV_SM_CLOCK{'
  register: dcgm_metrics_check
  failed_when: dcgm_metrics_check.rc != 0
  changed_when: false
