---
- name: Check for installed nvidia-driver RPM
  ansible.builtin.package_facts:
    manager: rpm

- name: Extract nvidia-driver version
  ansible.builtin.set_fact:
    _nvidia_driver_version_release: "{{ ansible_facts.packages['nvidia-driver'][0].version }}-{{ ansible_facts.packages['nvidia-driver'][0].release }}"
  when: "'nvidia-driver' in ansible_facts.packages"

- name: Set libnvidia-ml version based on nvidia-driver or fallback
  ansible.builtin.set_fact:
    _libnvidia_ml_version_release: "{{ _nvidia_driver_version_release | default(dcgm_exporter_libnvidia_ml_version_release_fallback) }}"
  when: dcgm_exporter_libnvidia_ml_version_release_force is not defined

- name: Set libnvidia-ml version based on force variable
  ansible.builtin.set_fact:
    _libnvidia_ml_version_release: "{{ dcgm_exporter_libnvidia_ml_version_release_force }}"
  when: dcgm_exporter_libnvidia_ml_version_release_force is defined

- name: Install NVIDIA Management Library RPM
  ansible.builtin.dnf:
    name: >-
      {{ dcgm_exporter_nvidia_repo_url -}}
      libnvidia-ml-{{ _libnvidia_ml_version_release }}.x86_64.rpm
    state: present
  notify: Restart dcgm-exporter