---
- name: Extract nvidia-driver version
  ansible.builtin.set_fact:
    _nvidia_driver_version_release: "{{ ansible_facts.packages['nvidia-driver'][0].version }}-{{ ansible_facts.packages['nvidia-driver'][0].release }}"

- name: Set Management Library package name for older drivers
  ansible.builtin.set_fact:
    dcgm_exporter_nvidia_ml_package_name: "nvidia-driver-NVML"
  when: _nvidia_driver_version_release | ansible.builtin.regex_replace('^(.*?)\\..*', '\\1') | int < 560

- name: Install NVIDIA Management Library RPM
  ansible.builtin.dnf:
    name: "{{ dcgm_exporter_nvidia_ml_package_name }}-{{ _nvidia_driver_version_release }}"
    state: present
  notify: Restart dcgm-exporter